# Configs
# Site Settings
title                     : "MetOncoFit"
description               : >
  "A Machine Learning Algorithm to Identify Common Biochemical and Topological Attributes of Metabolic Genes Recurrently Dysregulated in Tumors"
url                       : #'https://sriram-lab.github.io/MetOncoFit/'
baseurl                   : #
repository                : #
github                    : [metadata]

# Defaults
#defaults:
  # _pages
#  -
#    scope:
#      path: ""
#      type: pages
#    values:
#      layout: "default"
